import img1 from '../../assets/1.png'
const LocalsData = [
    {
      image: img1,
      name: "Conspire Contemporary Craft",
      lat: 39.6415,
      lng: -86.8618,
      shortDescription: "Handmade art, gifts, and local crafts in a cozy space.",
    },
    {
      image: img1,
      name: "Silver Bell Flowers",
      lat: 39.6418,
      lng: -86.8614,
      shortDescription: "Charming flower shop offering bouquets and custom arrangements.",
    },
    {
        image: img1,
        name: "TapHouse",
        lat: 39.6418,
        lng: -86.8614,
        shortDescription: "Casual spot for gourmet burgers and craft beer.",
    },
    {
      image: img1,
      name: "Britt’s Blooming Boutique",
      lat: 39.6413,
      lng: -86.8619,
      shortDescription: "Trendy boutique for women’s fashion and accessories.",
    },
    {
      image: img1,
      name: "Fluttering Duck",
      lat: 39.6411,
      lng: -86.8634,
      shortDescription: "Upscale pub food inside the Inn at DePauw.",
    },
    {
      image: img1,
      name: "Starbucks",
      lat: 39.6405,
      lng: -86.8642,
      shortDescription: "Familiar coffeehouse chain with roasts, pastries & WiFi.",
    },
    {
      image: img1,
      name: "Burdge Boots & Boutique",
      lat: 39.6421,
      lng: -86.8609,
      shortDescription: "Boots, western wear, and fashion-forward finds.",
    },
    {
      image: img1,
      name: "Almost Home",
      lat: 39.6417,
      lng: -86.8612,
      shortDescription: "Homestyle American restaurant known for comfort food.",
    },
    {
      image: img1,
      name: "Taco Wapo",
      lat: 39.6403,
      lng: -86.8651,
      shortDescription: "Local taco spot serving Mexican street food.",
    },
    {
      image: img1,
      name: "Don Julio",
      lat: 39.6401,
      lng: -86.8653,
      shortDescription: "Colorful Mexican restaurant offering margaritas & classics.",
    },
    {
      image: img1,
      name: "Lost Hollow Beer Co.",
      lat: 39.6407,
      lng: -86.8647,
      shortDescription: "Craft beer, good food & live music.",
    },
    {
      image: img1,
      name: "Marvin’s",
      lat: 39.6409,
      lng: -86.8656,
      shortDescription: "DePauw late-night legend with garlic cheeseburgers.",
    },
    {
      image: img1,
      name: "Blushing Beaus Boutique",
      lat: 39.6412,
      lng: -86.8615,
      shortDescription: "Trendy clothing and gift boutique downtown.",
    },
    {
      image: img1,
      name: "Antiques & Collectibles",
      lat: 39.6414,
      lng: -86.8611,
      shortDescription: "Vintage treasures and timeless décor finds.",
    },
    {
      image: img1,
      name: "The Whisk",
      lat: 39.6406,
      lng: -86.8645,
      shortDescription: "Bakery and café with espresso & pastries.",
    },
    {
      image: img1,
      name: "The Bodega",
      lat: 39.6408,
      lng: -86.8650,
      shortDescription: "Local market with snacks, drinks, and essentials.",
    },
    {
      image: img1,
      name: "Scoops Ice Cream Parlor",
      lat: 39.6402,
      lng: -86.8649,
      shortDescription: "Local favorite for hand-dipped ice cream.",
    },
    {
      image: img1,
      name: "Breadworks By Bridges",
      lat: 39.6410,
      lng: -86.8625,
      shortDescription: "Artisan bread and pastries made fresh daily.",
    },
  ];
  
  export default LocalsData;  